Added authorize transaction support
mcspronko/liqpay-magento2 pull request #49
Opened 2019-09-22 08:58 UTC by galanis-a

Added authorize transaction support.
Created config source for payment action.
Created payment action builder.
Removed payment action from general builder.

2019-09-22 18:10 UTC, mcspronko commented on admin/Source/PaymentAction.php
> + * @package Pronko\LiqPayAdmin\Source
Please remove @package comment.

2019-09-22 18:10 UTC, mcspronko commented on admin/Source/PaymentAction.php
> +     * Return array of options as value-label pairs
Comment on line 17 can be removed.

2019-09-22 18:10 UTC, mcspronko commented on admin/Source/PaymentAction.php
> +}
Please add empty line.

2019-09-22 18:10 UTC, mcspronko commented on gateway/Gateway/Request/Builder/PaymentActionBuilder.php
> + * @package Pronko\LiqPayGateway\Gateway\Request\Builder
Please remove the @package comment.

2019-09-22 18:10 UTC, mcspronko commented on gateway/Gateway/Request/Builder/PaymentActionBuilder.php
> +
Please remove an empty line.

2019-09-22 18:10 UTC, mcspronko commented on gateway/Gateway/Request/Builder/PaymentActionBuilder.php
> +}
Please add the empty line.

2019-09-22 18:11 UTC, mcspronko commented
@galanis-a all looks great, only a few formatting notes added. If you can have a look please.

2019-09-23 07:15 UTC, galanis-a commented
Thanks Max,

done withe formatting. Please check.

2019-09-23 07:37 UTC, mcspronko requested changes

2019-09-23 07:37 UTC, mcspronko commented on card-gateway/etc/di.xml
> +                <item name="paymentAction" xsi:type="string">Pronko\LiqPayCardGateway\Gateway\Request\Builder\PaymentActionBuilder</item>
The class namespace is used "LiqPayCardGateway" however the class is located in the "LiqPayGateway" if you can fix this.

2019-09-23 08:11 UTC, galanis-a commented
Yeah sorry about that. Fixed

2019-09-23 17:40 UTC, merged